# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .resource_py3 import Resource


class HcxEnterpriseSite(Resource):
    """An HCX Enterprise Site resource.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar id: Resource ID.
    :vartype id: str
    :ivar name: Resource name.
    :vartype name: str
    :ivar type: Resource type.
    :vartype type: str
    :ivar provisioning_state: The state of the HCX Enterprise Site
     provisioning. Possible values include: 'Succeeded', 'Failed', 'Updating'
    :vartype provisioning_state: str or
     ~vendored_sdks.models.HcxEnterpriseSiteProvisioningState
    :ivar activation_key: The activation key
    :vartype activation_key: str
    :ivar status: The status of the HCX Enterprise Site. Possible values
     include: 'Available', 'Consumed', 'Deactivated', 'Deleted'
    :vartype status: str or ~vendored_sdks.models.HcxEnterpriseSiteStatus
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'provisioning_state': {'readonly': True},
        'activation_key': {'readonly': True},
        'status': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'provisioning_state': {'key': 'properties.provisioningState', 'type': 'str'},
        'activation_key': {'key': 'properties.activationKey', 'type': 'str'},
        'status': {'key': 'properties.status', 'type': 'str'},
    }

    def __init__(self, **kwargs) -> None:
        super(HcxEnterpriseSite, self).__init__(**kwargs)
        self.provisioning_state = None
        self.activation_key = None
        self.status = None
