# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.paging import Paged


class IdentitySourcePaged(Paged):
    """
    A paging container for iterating over a list of :class:`IdentitySource <vendored_sdks.models.IdentitySource>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[IdentitySource]'}
    }

    def __init__(self, *args, **kwargs):

        super(IdentitySourcePaged, self).__init__(*args, **kwargs)
