# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PrivateCloudUpdate(Model):
    """The properties of a private cloud resource that may be updated.

    :param management_cluster: The default cluster used for management
    :type management_cluster: ~vendored_sdks.models.ManagementCluster
    :param internet: Connectivity to internet is enabled or disabled. Possible
     values include: 'Enabled', 'Disabled'
    :type internet: str or ~vendored_sdks.models.InternetEnum
    :param identity_sources: vCenter Single Sign On Identity Sources
    :type identity_sources: list[~vendored_sdks.models.IdentitySource]
    """

    _attribute_map = {
        'management_cluster': {'key': 'managementCluster', 'type': 'ManagementCluster'},
        'internet': {'key': 'internet', 'type': 'str'},
        'identity_sources': {'key': 'identitySources', 'type': '[IdentitySource]'},
    }

    def __init__(self, **kwargs):
        super(PrivateCloudUpdate, self).__init__(**kwargs)
        self.management_cluster = kwargs.get('management_cluster', None)
        self.internet = kwargs.get('internet', None)
        self.identity_sources = kwargs.get('identity_sources', None)
